### 1. Run the following cells: use these arrays for taskks

In [1]:
import numpy as np

In [2]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array([10, 11, 12, 13, 14])

In [3]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [4]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 2. Slice the first column of the 2-D array. 

In [17]:
array_2D[:,:1]

array([[20],
       [43],
       [11]])

### 3. Slice the last column of the 2-D array

In [18]:
array_2D[:,-1:]

array([[60],
       [87],
       [55]])

### 4. Slice the second row of the 2-D array

In [19]:
#array_2D[1]
array_2D[1:2,:]

array([[43, 54, 65, 76, 87]])

### 5. Slice the last two columns of the 2-nd row of the 2-D array

In [21]:
array_2D[1,-2:]

array([76, 87])

### 6. Slice the 1st, 3rd and 5th columns of the 2-D array
   (<b>Hint</b>: Take advantage of the [start:stop:step] sYntax of indices)

In [23]:
array_2D[:,::2]

array([[20, 40, 60],
       [43, 65, 87],
       [11, 33, 55]])

### 9. Generate 4 arrays of size 12:
    A) The first one should be "empty"
    B) The second one should be full of 0s
    C) The third one should be full of 1s
    D) The last one should be full of 50s


In [33]:
np.empty(shape=(12,))


array([1.19456403e-311, 2.42092166e-322, 0.00000000e+000, 0.00000000e+000,
       6.23053953e-307, 4.47032019e-038, 5.27991128e-091, 7.92560568e+165,
       4.28884149e-038, 2.94826789e+179, 6.99196248e+228, 8.15800118e-043])

In [36]:
np.zeros(shape=(12,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.ones(shape=(12,))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.full((12,), 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### 10. Generate 4 more arrays. This time, they should be 2 by 4 arrays. 

In [41]:
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
np.full((2,4),5, dtype=complex)

array([[5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j]])

In [45]:
np.zeros((2,4), dtype=str)

array([['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [61]:
np.full((8,), 'numpy', dtype='<U8').reshape(2,4)

array([['numpy', 'numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy', 'numpy']], dtype='<U8')

### 11. With the help of the np.arange() function, generate several sequences of numbers:
    A) The integers from 0 to 50, 
    B) The integers from 1 to 50, 
    C) The integers from 25 to 50,, 
    D) Every 5-th integers from 25 to 50, including 50. 
    E) Every 5-th integers from 25 to 50, including 50.

In [51]:
np.arange(51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [52]:
np.arange(1, 51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [53]:
np.arange(25, 51)

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50])

In [54]:
np.arange(25, 51, 5)

array([25, 30, 35, 40, 45, 50])

In [56]:
np.arange(50, 24, -5)

array([50, 45, 40, 35, 30, 25])

### 12. Import the following functions from the numpy.random module:
    A) Generator as "gen".
    B) PCG64 as "pcg"

In [58]:
from numpy.random import Generator as gen, PCG64 as pcg

### 13. Create a random generator object.

In [64]:
array_RG = gen(pcg())

### 14. Using the .random() method, generate the following pseudo-random values:

In [65]:
array_RG.random((5,5))

array([[0.5061256 , 0.69017169, 0.81753602, 0.08468011, 0.16950994],
       [0.82616446, 0.70674034, 0.80203059, 0.45821423, 0.49823017],
       [0.02870772, 0.76173471, 0.6709355 , 0.39355945, 0.64984412],
       [0.16363353, 0.34578642, 0.70947294, 0.73342117, 0.63213235],
       [0.41562914, 0.433174  , 0.67809247, 0.9754033 , 0.35170787]])

In [67]:
array_RG.integers(50, 100, (5,5))

array([[59, 61, 84, 71, 52],
       [63, 94, 68, 67, 71],
       [52, 55, 56, 95, 67],
       [95, 69, 83, 98, 62],
       [63, 62, 59, 55, 96]], dtype=int64)

In [76]:
array_RG.poisson(lam = 100., size=(20,))

array([103,  97, 101,  97, 110, 116,  98,  88,  93,  91,  96,  94,  90,
       102, 103,  95, 100, 109, 109,  86], dtype=int64)